SUPABASE_URL = "https://aqoyyetigfoubqnsewyj.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxb3l5ZXRpZ2ZvdWJxbnNld3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMjAwOTYsImV4cCI6MjA3MzU5NjA5Nn0.AwWMDbqhd5rRqu0vAsmvSGcNpAHdgG0v7Dupn66VuwU"
